# Dependencies
#markdown:            redcarpet
# http://www.webmaster-source.com/2013/06/26/how-to-enable-curly-quotes-in-jekyll/
markdown: rdiscount
rdiscount:
    extensions: ['smart']

#highlighter:         pygments
highlighter:         linguist
fenced_code_blocks:  true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Computing Thoughts
tagline:          Bruce Eckel's Programming Blog
url:              http://bruceeckel.github.io/
paginate:            5
baseurl:          /

# About/contact
author:
  name:           Bruce Eckel
  url:            http://www.mindviewinc.com
  email:          mindviewinc@gmail.com

