# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Computing Thoughts
tagline:          Bruce Eckel's Programming Blog
url:              http://bruceeckel.github.io/
paginate:         1
baseurl:          /
author:
  name:           Bruce Eckel
  url:            http://www.mindviewinc.com
  email:          mindviewinc@gmail.com

